-- Phase 1 schema: staff auth, leads, students (NEET profile), college & seat-matrix master data,
-- master-data change approval, audit log.
-- Kept portable between PostgreSQL (production) and H2 in PostgreSQL mode (tests).

CREATE TABLE app_user (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name       VARCHAR(120)  NOT NULL,
    email           VARCHAR(160)  NOT NULL,
    phone           VARCHAR(20),
    password_hash   VARCHAR(100)  NOT NULL,
    role            VARCHAR(30)   NOT NULL,
    active          BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_app_user_email UNIQUE (email)
);

CREATE TABLE refresh_token (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT        NOT NULL REFERENCES app_user (id),
    token_hash      VARCHAR(64)   NOT NULL,
    expires_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked         BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_refresh_token_hash UNIQUE (token_hash)
);
CREATE INDEX ix_refresh_token_user ON refresh_token (user_id);

CREATE TABLE referral_associate (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name       VARCHAR(120)  NOT NULL,
    phone           VARCHAR(20)   NOT NULL,
    district        VARCHAR(80),
    commission_rate NUMERIC(5, 2) NOT NULL DEFAULT 0,
    active          BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE student (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    apaar_id                  VARCHAR(20),
    full_name                 VARCHAR(120) NOT NULL,
    date_of_birth             DATE,
    gender                    VARCHAR(10),
    phone                     VARCHAR(20)  NOT NULL,
    email                     VARCHAR(160),
    parent_name               VARCHAR(120),
    parent_phone              VARCHAR(20),
    category                  VARCHAR(10)  NOT NULL,
    pwd                       BOOLEAN      NOT NULL DEFAULT FALSE,
    home_state                VARCHAR(40)  NOT NULL,
    domicile_status           VARCHAR(20)  NOT NULL,
    nationality               VARCHAR(10)  NOT NULL DEFAULT 'INDIAN',
    nri_sponsored             BOOLEAN      NOT NULL DEFAULT FALSE,
    neet_year                 INT,
    neet_roll_no              VARCHAR(20),
    neet_qualified            BOOLEAN      NOT NULL DEFAULT TRUE,
    neet_score                INT,
    neet_percentile           NUMERIC(10, 7),
    neet_air                  INT,
    category_rank             INT,
    category_cert_valid_until DATE,
    language_preference       VARCHAR(10)  NOT NULL DEFAULT 'ENGLISH',
    assigned_counsellor_id    BIGINT REFERENCES app_user (id),
    created_at                TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at                TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_student_neet_roll UNIQUE (neet_roll_no)
);
CREATE INDEX ix_student_counsellor ON student (assigned_counsellor_id);

CREATE TABLE lead (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name               VARCHAR(120) NOT NULL,
    phone                   VARCHAR(20)  NOT NULL,
    alt_phone               VARCHAR(20),
    email                   VARCHAR(160),
    neet_roll_no            VARCHAR(20),
    neet_score              INT,
    neet_air                INT,
    category                VARCHAR(10),
    home_state              VARCHAR(40),
    domicile_status         VARCHAR(20),
    source                  VARCHAR(30)  NOT NULL,
    referral_associate_id   BIGINT REFERENCES referral_associate (id),
    status                  VARCHAR(30)  NOT NULL,
    assigned_counsellor_id  BIGINT REFERENCES app_user (id),
    language_preference     VARCHAR(10)  NOT NULL DEFAULT 'ENGLISH',
    notes                   VARCHAR(2000),
    student_id              BIGINT REFERENCES student (id),
    created_by              BIGINT REFERENCES app_user (id),
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at              TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_lead_phone ON lead (phone);
CREATE INDEX ix_lead_neet_roll ON lead (neet_roll_no);
CREATE INDEX ix_lead_status ON lead (status);
CREATE INDEX ix_lead_counsellor ON lead (assigned_counsellor_id);

CREATE TABLE lead_activity (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id     BIGINT       NOT NULL REFERENCES lead (id),
    type        VARCHAR(20)  NOT NULL,
    outcome     VARCHAR(120),
    notes       VARCHAR(2000),
    created_by  BIGINT REFERENCES app_user (id),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_lead_activity_lead ON lead_activity (lead_id);

CREATE TABLE follow_up (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id       BIGINT       NOT NULL REFERENCES lead (id),
    assigned_to   BIGINT       NOT NULL REFERENCES app_user (id),
    due_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    purpose       VARCHAR(200) NOT NULL,
    completed_at  TIMESTAMP WITH TIME ZONE,
    completed_by  BIGINT REFERENCES app_user (id),
    created_by    BIGINT REFERENCES app_user (id),
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_follow_up_assignee_due ON follow_up (assigned_to, due_at);
CREATE INDEX ix_follow_up_lead ON follow_up (lead_id);

-- ---- College & seat-matrix master data (only ever holds APPROVED data) ----

CREATE TABLE college (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                  VARCHAR(200) NOT NULL,
    code                  VARCHAR(30),
    college_type          VARCHAR(20)  NOT NULL,
    state                 VARCHAR(40)  NOT NULL,
    city                  VARCHAR(80),
    affiliated_university VARCHAR(200),
    nmc_recognized        BOOLEAN      NOT NULL DEFAULT TRUE,
    established_year      INT,
    website               VARCHAR(200),
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_college_code UNIQUE (code)
);
CREATE INDEX ix_college_state ON college (state);

CREATE TABLE seat_matrix_entry (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    college_id        BIGINT      NOT NULL REFERENCES college (id),
    course            VARCHAR(10) NOT NULL,
    quota             VARCHAR(20) NOT NULL,
    category          VARCHAR(10) NOT NULL,
    pwd               BOOLEAN     NOT NULL DEFAULT FALSE,
    counselling_round VARCHAR(20) NOT NULL,
    academic_year     INT         NOT NULL,
    seats             INT         NOT NULL,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_seat_matrix UNIQUE (college_id, course, quota, category, pwd, counselling_round, academic_year),
    CONSTRAINT ck_seat_matrix_seats CHECK (seats >= 0)
);

CREATE TABLE college_fee (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    college_id      BIGINT         NOT NULL REFERENCES college (id),
    course          VARCHAR(10)    NOT NULL,
    quota           VARCHAR(20)    NOT NULL,
    academic_year   INT            NOT NULL,
    annual_tuition  NUMERIC(12, 2) NOT NULL,
    other_fees      NUMERIC(12, 2),
    notes           VARCHAR(500),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_college_fee UNIQUE (college_id, course, quota, academic_year),
    CONSTRAINT ck_college_fee_positive CHECK (annual_tuition >= 0)
);

CREATE TABLE cutoff_record (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    college_id        BIGINT      NOT NULL REFERENCES college (id),
    course            VARCHAR(10) NOT NULL,
    quota             VARCHAR(20) NOT NULL,
    category          VARCHAR(10) NOT NULL,
    pwd               BOOLEAN     NOT NULL DEFAULT FALSE,
    counselling_round VARCHAR(20) NOT NULL,
    academic_year     INT         NOT NULL,
    closing_rank      INT         NOT NULL,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_cutoff UNIQUE (college_id, course, quota, category, pwd, counselling_round, academic_year),
    CONSTRAINT ck_cutoff_rank CHECK (closing_rank > 0)
);
CREATE INDEX ix_cutoff_lookup ON cutoff_record (quota, category, academic_year, closing_rank);

-- Every change to master data goes through a change request that an admin approves.
CREATE TABLE data_change_request (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type   VARCHAR(20)  NOT NULL,
    entity_id     BIGINT,
    action        VARCHAR(20)  NOT NULL,
    summary       VARCHAR(300) NOT NULL,
    payload       TEXT         NOT NULL,
    status        VARCHAR(20)  NOT NULL,
    requested_by  BIGINT       NOT NULL REFERENCES app_user (id),
    requested_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    reviewed_by   BIGINT REFERENCES app_user (id),
    reviewed_at   TIMESTAMP WITH TIME ZONE,
    review_note   VARCHAR(500)
);
CREATE INDEX ix_change_request_status ON data_change_request (status);

CREATE TABLE audit_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id     BIGINT REFERENCES app_user (id),
    action       VARCHAR(40)  NOT NULL,
    entity_type  VARCHAR(30)  NOT NULL,
    entity_id    BIGINT,
    details      VARCHAR(2000),
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_audit_entity ON audit_log (entity_type, entity_id);
