-- Phase 2: counselling authorities & round calendar, per-student counselling tracks, choice lists,
-- allotments & decisions, predictor shortlists, and the alert pipeline (in-app notifications + outbound
-- student/parent messages).

CREATE TABLE counselling_authority (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(30)  NOT NULL,
    name            VARCHAR(200) NOT NULL,
    authority_type  VARCHAR(10)  NOT NULL,
    state           VARCHAR(40),
    website         VARCHAR(200),
    active          BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_authority_code UNIQUE (code),
    CONSTRAINT ck_authority_type CHECK (authority_type IN ('CENTRAL', 'STATE'))
);

-- One round of one authority in one academic year, with its deadlines (spec 4.5).
CREATE TABLE counselling_round (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    authority_id           BIGINT       NOT NULL REFERENCES counselling_authority (id),
    academic_year          INT          NOT NULL,
    round_type             VARCHAR(20)  NOT NULL,
    registration_start     TIMESTAMP WITH TIME ZONE,
    registration_end       TIMESTAMP WITH TIME ZONE,
    choice_filling_start   TIMESTAMP WITH TIME ZONE,
    choice_filling_end     TIMESTAMP WITH TIME ZONE,
    result_at              TIMESTAMP WITH TIME ZONE,
    reporting_start        TIMESTAMP WITH TIME ZONE,
    reporting_end          TIMESTAMP WITH TIME ZONE,
    notes                  VARCHAR(1000),
    updated_at             TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_round UNIQUE (authority_id, academic_year, round_type)
);

-- A student's participation in one authority's counselling for one year: AIQ and State run in parallel.
CREATE TABLE student_counselling (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id       BIGINT       NOT NULL REFERENCES student (id),
    authority_id     BIGINT       NOT NULL REFERENCES counselling_authority (id),
    academic_year    INT          NOT NULL,
    registration_no  VARCHAR(40),
    status           VARCHAR(20)  NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_student_counselling UNIQUE (student_id, authority_id, academic_year)
);
CREATE INDEX ix_student_counselling_authority ON student_counselling (authority_id, academic_year);

CREATE TABLE choice_list (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_counselling_id BIGINT       NOT NULL REFERENCES student_counselling (id),
    round_id               BIGINT       NOT NULL REFERENCES counselling_round (id),
    status                 VARCHAR(10)  NOT NULL,
    locked_at              TIMESTAMP WITH TIME ZONE,
    locked_by              BIGINT REFERENCES app_user (id),
    confirmed_by_name      VARCHAR(120),
    confirmation_method    VARCHAR(20),
    locked_snapshot        TEXT,
    updated_at             TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_choice_list UNIQUE (student_counselling_id, round_id)
);

CREATE TABLE choice_list_item (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    choice_list_id  BIGINT       NOT NULL REFERENCES choice_list (id) ON DELETE CASCADE,
    position        INT          NOT NULL,
    college_id      BIGINT       NOT NULL REFERENCES college (id),
    course          VARCHAR(10)  NOT NULL,
    quota           VARCHAR(20)  NOT NULL,
    note            VARCHAR(300),
    CONSTRAINT uq_choice_item_position UNIQUE (choice_list_id, position),
    CONSTRAINT uq_choice_item_option UNIQUE (choice_list_id, college_id, course, quota)
);

-- What the student got in a round and what they decided (spec 4.6). college_id NULL = no allotment.
CREATE TABLE allotment_result (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_counselling_id BIGINT       NOT NULL REFERENCES student_counselling (id),
    round_id               BIGINT       NOT NULL REFERENCES counselling_round (id),
    college_id             BIGINT REFERENCES college (id),
    course                 VARCHAR(10),
    quota                  VARCHAR(20),
    category               VARCHAR(10),
    recorded_by            BIGINT REFERENCES app_user (id),
    recorded_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    decision               VARCHAR(20),
    decision_deadline      TIMESTAMP WITH TIME ZONE,
    decided_at             TIMESTAMP WITH TIME ZONE,
    decided_by             BIGINT REFERENCES app_user (id),
    decision_note          VARCHAR(1000),
    CONSTRAINT uq_allotment UNIQUE (student_counselling_id, round_id)
);

CREATE TABLE predictor_shortlist (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id  BIGINT       NOT NULL REFERENCES student (id),
    college_id  BIGINT       NOT NULL REFERENCES college (id),
    course      VARCHAR(10)  NOT NULL,
    quota       VARCHAR(20)  NOT NULL,
    band        VARCHAR(10),
    note        VARCHAR(300),
    created_by  BIGINT REFERENCES app_user (id),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_shortlist UNIQUE (student_id, college_id, course, quota)
);

-- In-app alerts for staff. dedup_key stops the scheduler from raising the same alert twice.
CREATE TABLE notification (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id      BIGINT        NOT NULL REFERENCES app_user (id),
    student_id        BIGINT REFERENCES student (id),
    type              VARCHAR(40)   NOT NULL,
    priority          VARCHAR(10)   NOT NULL,
    title             VARCHAR(200)  NOT NULL,
    body              VARCHAR(1000),
    link              VARCHAR(200),
    dedup_key         VARCHAR(120),
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    read_at           TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_notification_dedup UNIQUE (recipient_id, dedup_key)
);
CREATE INDEX ix_notification_recipient ON notification (recipient_id, read_at);

-- Messages to students/parents (WhatsApp/SMS/email): the communication log (spec 4.9).
CREATE TABLE outbound_message (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id        BIGINT        NOT NULL REFERENCES student (id),
    channel           VARCHAR(10)   NOT NULL,
    recipient         VARCHAR(160)  NOT NULL,
    recipient_label   VARCHAR(20)   NOT NULL,
    template          VARCHAR(40)   NOT NULL,
    priority          VARCHAR(10)   NOT NULL,
    body              VARCHAR(1000) NOT NULL,
    status            VARCHAR(12)   NOT NULL,
    attempts          INT           NOT NULL DEFAULT 0,
    provider_ref      VARCHAR(120),
    last_error        VARCHAR(300),
    dedup_key         VARCHAR(120),
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    sent_at           TIMESTAMP WITH TIME ZONE,
    acknowledged_at   TIMESTAMP WITH TIME ZONE,
    acknowledged_by   BIGINT REFERENCES app_user (id),
    escalated_at      TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_outbound_dedup UNIQUE (dedup_key)
);
CREATE INDEX ix_outbound_status ON outbound_message (status, priority, created_at);
CREATE INDEX ix_outbound_student ON outbound_message (student_id);

-- The two authorities almost every Tamil Nadu client deals with. Others are added from the calendar screen.
INSERT INTO counselling_authority (code, name, authority_type, state, website, active, created_at)
VALUES ('MCC', 'Medical Counselling Committee (All India Quota, Deemed, Central)', 'CENTRAL', NULL,
        'https://mcc.nic.in', TRUE, CURRENT_TIMESTAMP),
       ('TN-SELECTION', 'Tamil Nadu Selection Committee (DME)', 'STATE', 'Tamil Nadu',
        'https://tnmedicalselection.net', TRUE, CURRENT_TIMESTAMP);
