-- Phase 3: documents & verification, consultancy fees & payments, commissions, helpdesk tickets,
-- refund rules, grievance register.

-- ---------------------------------------------------------------- documents (spec 4.7)

-- Checklist items. applies_when decides which students need it (configurable, spec 4.7).
CREATE TABLE document_type (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code             VARCHAR(40)  NOT NULL,
    name             VARCHAR(120) NOT NULL,
    applies_when     VARCHAR(20)  NOT NULL,
    requires_expiry  BOOLEAN      NOT NULL DEFAULT FALSE,
    sort_order       INT          NOT NULL DEFAULT 100,
    active           BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_document_type_code UNIQUE (code)
);

CREATE TABLE student_document (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id        BIGINT       NOT NULL REFERENCES student (id),
    document_type_id  BIGINT       NOT NULL REFERENCES document_type (id),
    status            VARCHAR(20)  NOT NULL,
    valid_until       DATE,
    notes             VARCHAR(500),
    verified_by       BIGINT REFERENCES app_user (id),
    verified_at       TIMESTAMP WITH TIME ZONE,
    updated_by        BIGINT REFERENCES app_user (id),
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_student_document UNIQUE (student_id, document_type_id)
);

-- Uploaded scans. Every upload is kept (versions); the newest is current.
CREATE TABLE document_file (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_document_id  BIGINT        NOT NULL REFERENCES student_document (id),
    storage_key          VARCHAR(200)  NOT NULL,
    original_name        VARCHAR(200)  NOT NULL,
    content_type         VARCHAR(60)   NOT NULL,
    size_bytes           BIGINT        NOT NULL,
    sha256               VARCHAR(64)   NOT NULL,
    uploaded_by          BIGINT REFERENCES app_user (id),
    uploaded_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_document_file_key UNIQUE (storage_key)
);
CREATE INDEX ix_document_file_doc ON document_file (student_document_id);

INSERT INTO document_type (code, name, applies_when, requires_expiry, sort_order) VALUES
    ('NEET_SCORECARD',     'NEET scorecard / rank letter',          'ALWAYS',            FALSE, 10),
    ('NEET_ADMIT_CARD',    'NEET admit card',                       'ALWAYS',            FALSE, 20),
    ('CLASS10_MARKSHEET',  'Class 10 marksheet (date of birth proof)', 'ALWAYS',         FALSE, 30),
    ('CLASS12_MARKSHEET',  'Class 12 marksheet',                    'ALWAYS',            FALSE, 40),
    ('TRANSFER_CERT',      'Transfer certificate',                  'ALWAYS',            FALSE, 50),
    ('AADHAAR',            'Aadhaar card',                          'ALWAYS',            FALSE, 60),
    ('PHOTOS',             'Passport-size photographs',             'ALWAYS',            FALSE, 70),
    ('CATEGORY_CERT',      'Community / category certificate',      'RESERVED_CATEGORY', TRUE,  80),
    ('EWS_CERT',           'EWS income & asset certificate',        'EWS',               TRUE,  90),
    ('NATIVITY_CERT',      'Nativity / domicile certificate',       'DOMICILED',         FALSE, 100),
    ('PWD_CERT',           'Disability certificate (designated centre)', 'PWD',          FALSE, 110),
    ('NRI_DOCS',           'NRI documents (passport, visa, sponsor affidavit)', 'NRI',   FALSE, 120),
    ('MIGRATION_CERT',     'Migration certificate (other boards)',  'OPTIONAL',          FALSE, 130),
    ('GAP_CERT',           'Gap certificate / affidavit',           'OPTIONAL',          FALSE, 140);

-- ---------------------------------------------------------------- fees (spec 4.8)

CREATE TABLE service_package (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(120)   NOT NULL,
    description   VARCHAR(1000),
    total_amount  NUMERIC(12, 2) NOT NULL,
    active        BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_package_amount CHECK (total_amount >= 0)
);

-- Default instalments of a package; due dates are offsets from the plan start.
CREATE TABLE package_installment (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    package_id       BIGINT         NOT NULL REFERENCES service_package (id) ON DELETE CASCADE,
    seq              INT            NOT NULL,
    label            VARCHAR(120)   NOT NULL,
    amount           NUMERIC(12, 2) NOT NULL,
    due_offset_days  INT            NOT NULL,
    CONSTRAINT uq_package_installment UNIQUE (package_id, seq)
);

CREATE TABLE fee_plan (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id    BIGINT         NOT NULL REFERENCES student (id),
    package_id    BIGINT REFERENCES service_package (id),
    name          VARCHAR(120)   NOT NULL,
    total_amount  NUMERIC(12, 2) NOT NULL,
    discount      NUMERIC(12, 2) NOT NULL DEFAULT 0,
    status        VARCHAR(12)    NOT NULL,
    notes         VARCHAR(1000),
    created_by    BIGINT REFERENCES app_user (id),
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_plan_amounts CHECK (total_amount >= 0 AND discount >= 0 AND discount <= total_amount)
);
CREATE INDEX ix_fee_plan_student ON fee_plan (student_id);

CREATE TABLE fee_installment (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id   BIGINT         NOT NULL REFERENCES fee_plan (id) ON DELETE CASCADE,
    seq       INT            NOT NULL,
    label     VARCHAR(120)   NOT NULL,
    amount    NUMERIC(12, 2) NOT NULL,
    due_date  DATE           NOT NULL,
    CONSTRAINT uq_fee_installment UNIQUE (plan_id, seq),
    CONSTRAINT ck_installment_amount CHECK (amount >= 0)
);
CREATE INDEX ix_fee_installment_due ON fee_installment (due_date);

CREATE SEQUENCE receipt_seq START WITH 1;

CREATE TABLE payment (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id         BIGINT         NOT NULL REFERENCES fee_plan (id),
    installment_id  BIGINT REFERENCES fee_installment (id),
    receipt_no      VARCHAR(30)    NOT NULL,
    amount          NUMERIC(12, 2) NOT NULL,
    method          VARCHAR(20)    NOT NULL,
    reference       VARCHAR(100),
    paid_on         DATE           NOT NULL,
    notes           VARCHAR(500),
    received_by     BIGINT REFERENCES app_user (id),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    voided          BOOLEAN        NOT NULL DEFAULT FALSE,
    void_reason     VARCHAR(300),
    voided_by       BIGINT REFERENCES app_user (id),
    CONSTRAINT uq_payment_receipt UNIQUE (receipt_no),
    CONSTRAINT ck_payment_amount CHECK (amount > 0)
);
CREATE INDEX ix_payment_plan ON payment (plan_id);

CREATE TABLE fee_refund (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id       BIGINT         NOT NULL REFERENCES fee_plan (id),
    amount        NUMERIC(12, 2) NOT NULL,
    reason        VARCHAR(1000)  NOT NULL,
    status        VARCHAR(12)    NOT NULL,
    requested_by  BIGINT REFERENCES app_user (id),
    requested_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    decided_by    BIGINT REFERENCES app_user (id),
    decided_at    TIMESTAMP WITH TIME ZONE,
    decision_note VARCHAR(500),
    paid_on       DATE,
    paid_reference VARCHAR(100),
    CONSTRAINT ck_refund_amount CHECK (amount > 0)
);

-- Referral-associate commission, created when a referred lead's admission is confirmed.
CREATE TABLE commission_entry (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    associate_id   BIGINT         NOT NULL REFERENCES referral_associate (id),
    lead_id        BIGINT         NOT NULL REFERENCES lead (id),
    student_id     BIGINT REFERENCES student (id),
    basis_amount   NUMERIC(12, 2) NOT NULL,
    rate           NUMERIC(5, 2)  NOT NULL,
    amount         NUMERIC(12, 2) NOT NULL,
    status         VARCHAR(12)    NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    paid_on        DATE,
    paid_reference VARCHAR(100),
    CONSTRAINT uq_commission_lead UNIQUE (associate_id, lead_id)
);

-- ---------------------------------------------------------------- helpdesk (spec 4.14)

CREATE TABLE ticket (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id       BIGINT REFERENCES student (id),
    lead_id          BIGINT REFERENCES lead (id),
    raised_by_name   VARCHAR(120),
    raised_via       VARCHAR(12)   NOT NULL,
    subject          VARCHAR(200)  NOT NULL,
    description      VARCHAR(4000),
    category         VARCHAR(20)   NOT NULL,
    priority         VARCHAR(10)   NOT NULL,
    deadline_linked  BOOLEAN       NOT NULL DEFAULT FALSE,
    status           VARCHAR(20)   NOT NULL,
    assigned_to      BIGINT REFERENCES app_user (id),
    due_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    resolution       VARCHAR(2000),
    resolved_at      TIMESTAMP WITH TIME ZONE,
    created_by       BIGINT REFERENCES app_user (id),
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_ticket_status_due ON ticket (status, due_at);
CREATE INDEX ix_ticket_assignee ON ticket (assigned_to);

CREATE TABLE ticket_comment (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id   BIGINT        NOT NULL REFERENCES ticket (id),
    author_id   BIGINT REFERENCES app_user (id),
    body        VARCHAR(4000) NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_ticket_comment_ticket ON ticket_comment (ticket_id);

-- ---------------------------------------------------------------- refund rules (spec 4.27)

-- What a student loses by withdrawing. Most specific matching rule wins (college > authority+round >
-- authority). Tiers: several rows with increasing max_days_after_allotment.
CREATE TABLE refund_rule (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    authority_id              BIGINT REFERENCES counselling_authority (id),
    college_id                BIGINT REFERENCES college (id),
    round_type                VARCHAR(20),
    academic_year             INT           NOT NULL,
    max_days_after_allotment  INT,
    deposit_forfeited         BOOLEAN       NOT NULL,
    deposit_amount            NUMERIC(12, 2),
    tuition_refund_percent    NUMERIC(5, 2) NOT NULL,
    barred_from_later_rounds  BOOLEAN       NOT NULL DEFAULT FALSE,
    source                    VARCHAR(300)  NOT NULL,
    notes                     VARCHAR(1000),
    updated_at                TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_refund_percent CHECK (tuition_refund_percent >= 0 AND tuition_refund_percent <= 100),
    CONSTRAINT ck_refund_scope CHECK (authority_id IS NOT NULL OR college_id IS NOT NULL)
);
CREATE INDEX ix_refund_rule_scope ON refund_rule (academic_year, authority_id, college_id);

-- ---------------------------------------------------------------- grievances (spec 4.28)

CREATE SEQUENCE grievance_seq START WITH 1;

CREATE TABLE grievance (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference_no             VARCHAR(30)    NOT NULL,
    student_id               BIGINT REFERENCES student (id),
    ticket_id                BIGINT REFERENCES ticket (id),
    complainant_name         VARCHAR(120)   NOT NULL,
    complainant_phone        VARCHAR(20),
    category                 VARCHAR(20)    NOT NULL,
    description              VARCHAR(4000)  NOT NULL,
    amount_in_dispute        NUMERIC(12, 2),
    received_via             VARCHAR(12)    NOT NULL,
    received_at              TIMESTAMP WITH TIME ZONE NOT NULL,
    status                   VARCHAR(20)    NOT NULL,
    assigned_officer_id      BIGINT REFERENCES app_user (id),
    target_resolution_date   DATE           NOT NULL,
    resolution               VARCHAR(4000),
    resolved_at              TIMESTAMP WITH TIME ZONE,
    created_by               BIGINT REFERENCES app_user (id),
    created_at               TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_grievance_ref UNIQUE (reference_no)
);
CREATE INDEX ix_grievance_status ON grievance (status);

-- Append-only trail of everything done on a grievance.
CREATE TABLE grievance_action (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grievance_id  BIGINT        NOT NULL REFERENCES grievance (id),
    actor_id      BIGINT REFERENCES app_user (id),
    action_type   VARCHAR(20)   NOT NULL,
    details       VARCHAR(4000),
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_grievance_action ON grievance_action (grievance_id);
