-- Phase 4: branches, marketing campaigns, sub-agent network, alumni, student/parent portal.

-- ---------------------------------------------------------------- branches (spec 4.15)

CREATE TABLE branch (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(120) NOT NULL,
    code        VARCHAR(20)  NOT NULL,
    city        VARCHAR(80),
    state       VARCHAR(40),
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_branch_code UNIQUE (code)
);

-- A staff member with a branch only sees that branch's leads and students. No branch = head office (all).
ALTER TABLE app_user ADD COLUMN branch_id BIGINT REFERENCES branch (id);
ALTER TABLE lead ADD COLUMN branch_id BIGINT REFERENCES branch (id);
ALTER TABLE student ADD COLUMN branch_id BIGINT REFERENCES branch (id);
CREATE INDEX ix_lead_branch ON lead (branch_id);
CREATE INDEX ix_student_branch ON student (branch_id);

-- ---------------------------------------------------------------- marketing (spec 4.12)

CREATE TABLE campaign (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(120)   NOT NULL,
    channel     VARCHAR(30)    NOT NULL,
    branch_id   BIGINT REFERENCES branch (id),
    start_date  DATE,
    end_date    DATE,
    budget      NUMERIC(12, 2),
    notes       VARCHAR(1000),
    active      BOOLEAN        NOT NULL DEFAULT TRUE,
    created_by  BIGINT REFERENCES app_user (id),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE campaign_spend (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id  BIGINT         NOT NULL REFERENCES campaign (id),
    spent_on     DATE           NOT NULL,
    amount       NUMERIC(12, 2) NOT NULL,
    note         VARCHAR(300),
    created_by   BIGINT REFERENCES app_user (id),
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_campaign_spend_positive CHECK (amount > 0)
);
CREATE INDEX ix_campaign_spend_campaign ON campaign_spend (campaign_id);

ALTER TABLE lead ADD COLUMN campaign_id BIGINT REFERENCES campaign (id);
-- Past-student referrals (spec 4.23 feeding 4.12).
ALTER TABLE lead ADD COLUMN referred_by_student_id BIGINT REFERENCES student (id);
CREATE INDEX ix_lead_campaign ON lead (campaign_id);

-- ---------------------------------------------------------------- sub-agent network (spec 4.22)

ALTER TABLE referral_associate ADD COLUMN email VARCHAR(160);
ALTER TABLE referral_associate ADD COLUMN state VARCHAR(40);
ALTER TABLE referral_associate ADD COLUMN territory VARCHAR(300);
ALTER TABLE referral_associate ADD COLUMN agreement_start DATE;
ALTER TABLE referral_associate ADD COLUMN agreement_end DATE;
ALTER TABLE referral_associate ADD COLUMN agreement_terms VARCHAR(1000);
ALTER TABLE referral_associate ADD COLUMN branch_id BIGINT REFERENCES branch (id);

-- ---------------------------------------------------------------- alumni (spec 4.23)

CREATE TABLE alumni (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id       BIGINT       NOT NULL REFERENCES student (id),
    college_id       BIGINT REFERENCES college (id),
    college_name     VARCHAR(200) NOT NULL,
    course           VARCHAR(10)  NOT NULL,
    quota            VARCHAR(20),
    admission_year   INT          NOT NULL,
    willing_to_refer BOOLEAN      NOT NULL DEFAULT FALSE,
    notes            VARCHAR(1000),
    created_by       BIGINT REFERENCES app_user (id),
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_alumni_student UNIQUE (student_id)
);

CREATE TABLE alumni_survey (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alumni_id          BIGINT  NOT NULL REFERENCES alumni (id),
    overall_rating     INT     NOT NULL,
    counsellor_rating  INT,
    would_recommend    BOOLEAN NOT NULL,
    comments           VARCHAR(2000),
    recorded_by        BIGINT REFERENCES app_user (id),
    recorded_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_alumni_survey_overall CHECK (overall_rating BETWEEN 1 AND 5),
    CONSTRAINT ck_alumni_survey_counsellor CHECK (counsellor_rating IS NULL OR counsellor_rating BETWEEN 1 AND 5)
);
CREATE INDEX ix_alumni_survey_alumni ON alumni_survey (alumni_id);

-- A testimonial may only be used publicly when the family consented AND an admin approved it.
CREATE TABLE testimonial (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alumni_id    BIGINT        NOT NULL REFERENCES alumni (id),
    quote        VARCHAR(2000) NOT NULL,
    consent      BOOLEAN       NOT NULL DEFAULT FALSE,
    status       VARCHAR(20)   NOT NULL,
    recorded_by  BIGINT REFERENCES app_user (id),
    reviewed_by  BIGINT REFERENCES app_user (id),
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_testimonial_alumni ON testimonial (alumni_id);

-- ---------------------------------------------------------------- student & parent portal (spec 4.10)

-- One login per phone number; it can be linked to several students (e.g. a parent with two children).
CREATE TABLE portal_account (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone                  VARCHAR(20)  NOT NULL,
    display_name           VARCHAR(120) NOT NULL,
    password_hash          VARCHAR(100),
    activation_code_hash   VARCHAR(100),
    activation_expires_at  TIMESTAMP WITH TIME ZONE,
    active                 BOOLEAN      NOT NULL DEFAULT TRUE,
    last_login_at          TIMESTAMP WITH TIME ZONE,
    created_by             BIGINT REFERENCES app_user (id),
    created_at             TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_portal_account_phone UNIQUE (phone)
);

CREATE TABLE portal_account_student (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id  BIGINT      NOT NULL REFERENCES portal_account (id),
    student_id  BIGINT      NOT NULL REFERENCES student (id),
    relation    VARCHAR(10) NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_portal_account_student UNIQUE (account_id, student_id)
);
CREATE INDEX ix_portal_account_student_student ON portal_account_student (student_id);

CREATE TABLE portal_refresh_token (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id  BIGINT      NOT NULL REFERENCES portal_account (id),
    token_hash  VARCHAR(64) NOT NULL,
    expires_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked     BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_portal_refresh_token_hash UNIQUE (token_hash)
);
CREATE INDEX ix_portal_refresh_token_account ON portal_refresh_token (account_id);

-- Files and tickets that came in through the portal have no staff author; remember the portal login instead.
ALTER TABLE document_file ADD COLUMN portal_account_id BIGINT REFERENCES portal_account (id);
ALTER TABLE ticket ADD COLUMN portal_account_id BIGINT REFERENCES portal_account (id);
