-- Phase 5: education loans, counselling sessions (video), call log, agreements & consent, FAQ knowledge
-- base for the website assistant, DigiLocker-ready document source.

-- ---------------------------------------------------------------- education loans (spec 4.26)

-- Lenders the firm refers students to. Rates shown are reference-only; the firm does not underwrite.
CREATE TABLE loan_partner (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(120) NOT NULL,
    interest_info  VARCHAR(200),
    max_amount     NUMERIC(12, 2),
    eligibility    VARCHAR(1000),
    contact_name   VARCHAR(120),
    contact_phone  VARCHAR(20),
    active         BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE loan_application (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id         BIGINT         NOT NULL REFERENCES student (id),
    partner_id         BIGINT         NOT NULL REFERENCES loan_partner (id),
    amount_requested   NUMERIC(12, 2) NOT NULL,
    amount_sanctioned  NUMERIC(12, 2),
    status             VARCHAR(20)    NOT NULL,
    -- The date the money must be available by, normally the college reporting deadline.
    needed_by          DATE,
    applied_on         DATE,
    decided_on         DATE,
    reference_no       VARCHAR(60),
    co_applicant       VARCHAR(120),
    notes              VARCHAR(2000),
    handled_by         BIGINT REFERENCES app_user (id),
    created_by         BIGINT REFERENCES app_user (id),
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_loan_amount CHECK (amount_requested > 0)
);
CREATE INDEX ix_loan_application_student ON loan_application (student_id);
CREATE INDEX ix_loan_application_status ON loan_application (status);

-- ---------------------------------------------------------------- counselling sessions (spec 4.19)

CREATE TABLE counselling_session (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id         BIGINT       NOT NULL REFERENCES student (id),
    host_id            BIGINT       NOT NULL REFERENCES app_user (id),
    mode               VARCHAR(20)  NOT NULL,
    scheduled_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    duration_minutes   INT          NOT NULL,
    topic              VARCHAR(200) NOT NULL,
    meeting_url        VARCHAR(500),
    status             VARCHAR(20)  NOT NULL,
    notes              VARCHAR(4000),
    recording_consent  BOOLEAN      NOT NULL DEFAULT FALSE,
    recording_url      VARCHAR(500),
    created_by         BIGINT REFERENCES app_user (id),
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at         TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_session_student ON counselling_session (student_id);
CREATE INDEX ix_session_host_time ON counselling_session (host_id, scheduled_at);

-- ---------------------------------------------------------------- call log (spec 4.21)

-- One row per call attempt to a lead or student. provider_* columns are filled by a telephony provider
-- (Exotel/Knowlarity) once connected; until then staff dial from their phone and record the outcome.
CREATE TABLE call_log (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id           BIGINT REFERENCES lead (id),
    student_id        BIGINT REFERENCES student (id),
    phone             VARCHAR(20) NOT NULL,
    direction         VARCHAR(10) NOT NULL,
    outcome           VARCHAR(20) NOT NULL,
    duration_seconds  INT,
    notes             VARCHAR(2000),
    provider          VARCHAR(30),
    provider_call_id  VARCHAR(80),
    recording_url     VARCHAR(500),
    called_by         BIGINT REFERENCES app_user (id),
    called_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_call_log_target CHECK (lead_id IS NOT NULL OR student_id IS NOT NULL)
);
CREATE INDEX ix_call_log_lead ON call_log (lead_id);
CREATE INDEX ix_call_log_student ON call_log (student_id);
CREATE INDEX ix_call_log_caller_time ON call_log (called_by, called_at);

-- ---------------------------------------------------------------- agreements & consent (spec 4.20)

CREATE TABLE agreement_template (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind        VARCHAR(30)   NOT NULL,
    title       VARCHAR(200)  NOT NULL,
    body        VARCHAR(20000) NOT NULL,
    active      BOOLEAN       NOT NULL DEFAULT TRUE,
    updated_by  BIGINT REFERENCES app_user (id),
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

-- The exact text the family agreed to is copied here, so later template edits never change what was signed.
CREATE TABLE student_agreement (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id         BIGINT        NOT NULL REFERENCES student (id),
    template_id        BIGINT REFERENCES agreement_template (id),
    kind               VARCHAR(30)   NOT NULL,
    title              VARCHAR(200)  NOT NULL,
    body               VARCHAR(20000) NOT NULL,
    body_sha256        VARCHAR(64)   NOT NULL,
    status             VARCHAR(20)   NOT NULL,
    sign_method        VARCHAR(30),
    signer_name        VARCHAR(120),
    signer_relation    VARCHAR(20),
    signed_at          TIMESTAMP WITH TIME ZONE,
    signer_ip          VARCHAR(45),
    portal_account_id  BIGINT REFERENCES portal_account (id),
    provider_ref       VARCHAR(120),
    issued_by          BIGINT REFERENCES app_user (id),
    issued_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    recorded_by        BIGINT REFERENCES app_user (id)
);
CREATE INDEX ix_student_agreement_student ON student_agreement (student_id);

INSERT INTO agreement_template (kind, title, body, active, updated_at) VALUES
('SERVICE_AGREEMENT', 'Counselling service agreement',
'This agreement is between {{orgName}} ("the Consultancy") and {{studentName}} ("the Student"), represented where the Student is a minor by the parent or guardian named below.

1. Service. The Consultancy will guide the Student through MBBS/BDS admission counselling for the {{neetYear}} session: explaining the process, preparing the college choice list, tracking round dates and results, and helping with documents.

2. No guarantee of a seat. Seat allotment is decided only by the counselling authorities (MCC and State authorities) on the basis of rank, category, and seat availability. The Consultancy does not and cannot guarantee admission to any college or course. College predictions are estimates based on previous years.

3. Decisions are the family''s. Locking a choice list, and accepting, upgrading, or giving up an allotted seat, are done only after the Student or parent confirms. The Consultancy will explain the consequences, including possible loss of the security deposit, before each decision.

4. Fees. The consultancy fee and instalment dates are as recorded in the fee plan shared with the family. Fees paid to colleges or counselling authorities are separate and are paid by the family directly.

5. Refunds. Refund of the consultancy fee follows the refund terms explained at enrolment and recorded with the fee plan.

6. Documents and accuracy. The family will provide true and complete information and documents on time. The Consultancy is not responsible for a missed round caused by late or incorrect documents or payments from the family.

7. Communication. Deadline alerts are sent by WhatsApp, SMS, phone call, and the student portal to the numbers on record. The family will keep these numbers reachable during counselling.

8. Grievances. Any complaint can be raised with the counsellor or through the portal and will be recorded and answered.

Signed by the Student / parent or guardian on the date recorded with this agreement.', TRUE, CURRENT_TIMESTAMP),
('DATA_CONSENT', 'Consent to use personal data',
'I, the undersigned, give {{orgName}} permission to collect, store, and use the personal data of {{studentName}}, including NEET details, category and income certificates, Aadhaar, marksheets, photographs, and contact numbers of the student and parents.

Purpose. The data will be used only to provide admission counselling: checking eligibility, filling counselling forms, preparing and submitting documents, sending deadline alerts, and keeping records of the service.

Sharing. The data may be shared with the counselling authorities and colleges where the Student applies, and with a lender only if I ask for an education loan. It will not be sold or used for unrelated marketing.

Retention. Records are kept for as long as needed for the service and for legal and dispute purposes, and are then deleted or anonymised.

My rights. I can ask to see, correct, or delete this data, or withdraw this consent, by contacting the Consultancy. Withdrawing consent may mean the service cannot continue.

I confirm that I am the Student (if 18 or older) or the Student''s parent or lawful guardian.', TRUE, CURRENT_TIMESTAMP);

-- ---------------------------------------------------------------- website assistant (spec 4.17, 4.25)

-- One shared FAQ knowledge base for the website assistant now and the voice agent later.
CREATE TABLE faq_entry (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language    VARCHAR(10)   NOT NULL,
    question    VARCHAR(300)  NOT NULL,
    answer      VARCHAR(2000) NOT NULL,
    keywords    VARCHAR(500),
    sort_order  INT           NOT NULL DEFAULT 100,
    active      BOOLEAN       NOT NULL DEFAULT TRUE,
    updated_by  BIGINT REFERENCES app_user (id),
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_faq_language ON faq_entry (language, active);

INSERT INTO faq_entry (language, question, answer, keywords, sort_order, updated_at) VALUES
('ENGLISH', 'What is the difference between All India Quota and State Quota?',
 'All India Quota (AIQ) covers 15% of government college seats across India and is run by MCC; any NEET-qualified student can apply. State Quota covers the remaining 85% and is run by each state for students who meet that state''s domicile rules. Most students take part in both.',
 'aiq, all india, state quota, mcc, 15, 85, difference', 10, CURRENT_TIMESTAMP),
('ENGLISH', 'Can you guarantee a seat?',
 'No. Seats are allotted only by the counselling authorities based on rank, category and availability. We help you make the best possible choices and never miss a deadline, but nobody can honestly guarantee a seat.',
 'guarantee, sure, confirm seat, assured', 20, CURRENT_TIMESTAMP),
('ENGLISH', 'Which documents are needed for counselling?',
 'Usually: NEET scorecard and admit card, Class 10 and 12 marksheets, transfer certificate, Aadhaar, passport photos, and where they apply the community, EWS, nativity or disability certificates. Your counsellor gives you the exact checklist for your category and state.',
 'documents, certificate, papers, marksheet, aadhaar, checklist', 30, CURRENT_TIMESTAMP),
('ENGLISH', 'What do freeze, float and withdraw mean?',
 'After a seat is allotted you can accept it as final (freeze), accept it but try for a better college in the next round (float), or give it up (withdraw). Giving up a seat after certain rounds can cost you the security deposit and bar you from later rounds, so always decide with your counsellor.',
 'freeze, float, withdraw, upgrade, slide, exit, security deposit', 40, CURRENT_TIMESTAMP),
('ENGLISH', 'How do I talk to a counsellor?',
 'Share your name, phone number and NEET score here and a counsellor will call you, usually within one working day.',
 'talk, call, contact, counsellor, speak, human', 50, CURRENT_TIMESTAMP),
('TAMIL', 'அகில இந்திய ஒதுக்கீடு மற்றும் மாநில ஒதுக்கீடு இடையே என்ன வேறுபாடு?',
 'அகில இந்திய ஒதுக்கீடு (AIQ) என்பது அரசு கல்லூரி இடங்களில் 15%; இதை MCC நடத்துகிறது, NEET தகுதி பெற்ற எவரும் விண்ணப்பிக்கலாம். மீதமுள்ள 85% மாநில ஒதுக்கீடு; அந்த மாநிலத்தின் இருப்பிட விதிகளை பூர்த்தி செய்பவர்களுக்கு மாநில அரசு நடத்துகிறது. பெரும்பாலான மாணவர்கள் இரண்டிலும் பங்கேற்கிறார்கள்.',
 'aiq, அகில இந்திய, மாநில, ஒதுக்கீடு, mcc', 10, CURRENT_TIMESTAMP),
('TAMIL', 'இடம் கிடைக்கும் என்று உத்தரவாதம் தர முடியுமா?',
 'முடியாது. தரவரிசை, பிரிவு மற்றும் காலியிடங்களின் அடிப்படையில் கலந்தாய்வு அதிகாரிகள் மட்டுமே இடங்களை ஒதுக்குகிறார்கள். சிறந்த தேர்வுகளைச் செய்யவும், எந்த கடைசி தேதியையும் தவறவிடாமல் இருக்கவும் நாங்கள் உதவுகிறோம்.',
 'உத்தரவாதம், உறுதி, guarantee', 20, CURRENT_TIMESTAMP),
('TAMIL', 'கலந்தாய்வுக்கு என்ன ஆவணங்கள் தேவை?',
 'பொதுவாக: NEET மதிப்பெண் அட்டை மற்றும் அனுமதி அட்டை, 10 மற்றும் 12-ஆம் வகுப்பு மதிப்பெண் சான்றிதழ்கள், மாற்றுச் சான்றிதழ், ஆதார், புகைப்படங்கள்; பொருந்தினால் சாதி, EWS, இருப்பிட அல்லது மாற்றுத்திறனாளி சான்றிதழ்கள். உங்கள் ஆலோசகர் சரியான பட்டியலைத் தருவார்.',
 'ஆவணங்கள், சான்றிதழ், documents', 30, CURRENT_TIMESTAMP),
('TAMIL', 'ஆலோசகரிடம் எப்படி பேசுவது?',
 'உங்கள் பெயர், தொலைபேசி எண் மற்றும் NEET மதிப்பெண்ணை இங்கே பகிருங்கள்; ஆலோசகர் பொதுவாக ஒரு வேலை நாளுக்குள் உங்களை அழைப்பார்.',
 'பேச, அழை, ஆலோசகர், call', 50, CURRENT_TIMESTAMP),
('HINDI', 'ऑल इंडिया कोटा और स्टेट कोटा में क्या अंतर है?',
 'ऑल इंडिया कोटा (AIQ) सरकारी कॉलेजों की 15% सीटों के लिए है और इसे MCC चलाता है; NEET उत्तीर्ण कोई भी छात्र आवेदन कर सकता है। बाकी 85% स्टेट कोटा है, जिसे हर राज्य अपने निवास नियम पूरे करने वाले छात्रों के लिए चलाता है। अधिकतर छात्र दोनों में भाग लेते हैं।',
 'aiq, ऑल इंडिया, स्टेट, कोटा, mcc', 10, CURRENT_TIMESTAMP),
('HINDI', 'क्या आप सीट की गारंटी दे सकते हैं?',
 'नहीं। सीटें केवल काउंसलिंग प्राधिकरण रैंक, श्रेणी और उपलब्धता के आधार पर देते हैं। हम आपको सबसे अच्छे विकल्प चुनने और कोई भी अंतिम तिथि न चूकने में मदद करते हैं।',
 'गारंटी, पक्का, guarantee', 20, CURRENT_TIMESTAMP),
('HINDI', 'काउंसलिंग के लिए कौन से दस्तावेज़ चाहिए?',
 'आम तौर पर: NEET स्कोरकार्ड और एडमिट कार्ड, कक्षा 10 और 12 की मार्कशीट, ट्रांसफर सर्टिफिकेट, आधार, फोटो; और जहाँ लागू हो वहाँ जाति, EWS, निवास या दिव्यांगता प्रमाणपत्र। आपका काउंसलर आपको सही सूची देगा।',
 'दस्तावेज़, प्रमाणपत्र, documents', 30, CURRENT_TIMESTAMP),
('HINDI', 'काउंसलर से कैसे बात करें?',
 'अपना नाम, फ़ोन नंबर और NEET स्कोर यहाँ साझा करें; काउंसलर आम तौर पर एक कार्य दिवस के भीतर आपको कॉल करेगा।',
 'बात, कॉल, काउंसलर, call', 50, CURRENT_TIMESTAMP);

-- ---------------------------------------------------------------- DigiLocker readiness (spec 4.16)

-- Where a file came from. DIGILOCKER files are issuer-signed and need no manual verification; nothing
-- writes that value until the DigiLocker integration is approved and connected.
ALTER TABLE document_file ADD COLUMN source VARCHAR(20) NOT NULL DEFAULT 'UPLOAD';
ALTER TABLE document_file ADD COLUMN issuer_verified BOOLEAN NOT NULL DEFAULT FALSE;
