-- Staff sign in with their mobile number and a one-time code.

-- One staff member per mobile number (several without a number are still allowed).
ALTER TABLE app_user ADD CONSTRAINT uq_app_user_phone UNIQUE (phone);

-- Only the hash of a code is kept. A code works once, for a few minutes, and a few wrong tries cancel it.
CREATE TABLE login_otp (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL REFERENCES app_user (id),
    code_hash   VARCHAR(100) NOT NULL,
    expires_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    attempts    INT          NOT NULL DEFAULT 0,
    used        BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_login_otp_user ON login_otp (user_id);
