-- One common login (mobile number + one-time code) for the admin, staff and students/parents.
-- Only students register themselves; staff accounts are created by the single admin.

-- One-time codes now serve staff and portal logins alike.
DROP TABLE login_otp;
CREATE TABLE login_otp (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_type  VARCHAR(10)  NOT NULL,
    subject_id    BIGINT       NOT NULL,
    code_hash     VARCHAR(100) NOT NULL,
    expires_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    attempts      INT          NOT NULL DEFAULT 0,
    used          BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_login_otp_subject ON login_otp (subject_type, subject_id);

-- Staff can no longer register themselves: drop requests that were never approved, and the flag.
DELETE FROM app_user WHERE pending_approval = TRUE;
ALTER TABLE app_user DROP COLUMN pending_approval;

-- There is exactly one admin: the first one. Any other admin account becomes an inactive counsellor.
UPDATE app_user SET role = 'COUNSELLOR', active = FALSE
WHERE role = 'SUPER_ADMIN'
  AND id <> (SELECT first_admin FROM (SELECT MIN(id) AS first_admin FROM app_user WHERE role = 'SUPER_ADMIN') a);

-- Portal logins use the one-time code too, so they have no password or activation code any more.
ALTER TABLE portal_account DROP COLUMN password_hash;
ALTER TABLE portal_account DROP COLUMN activation_code_hash;
ALTER TABLE portal_account DROP COLUMN activation_expires_at;
